import type { Metadata } from "next";
import { Baloo_2, Roboto } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { OrderProvider } from "@/contexts/OrderContext";
import { CartProvider } from "@/contexts/CartContext";

const baloo2 = Baloo_2({
  subsets: ['latin'],
  variable: '--font-baloo2'
})

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '800'],
  subsets: ['latin'],
  variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: "Coffee Delivery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${baloo2.variable} ${roboto.variable} antialiased`}
      >
        <OrderProvider>
          <CartProvider>
            <Header />
            {children}
          </CartProvider>
        </OrderProvider>
      </body>
    </html>
  );
}
